/* LOG IN/OUT/FAIL */
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

/* GET/EDIT PROFILE */
export const GET_USERPROFILE = "GET_USERPROFILE";
export const EDIT_PSEUDO = "EDIT_PSEUDO";