swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

#!transactions :

  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Retrieve monthly transactions
      description: User monthly transactions
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successully
          schema:
            type: array
            items:
              $ref: '#/definitions/Account'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Specific transaction
      description: User specific transaction
      parameters:
        - in: path
          name: id
          description: Transaction id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successully
          schema:
            $ref: '#/definitions/SpecificTransaction'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update transaction
      description: Update transaction
      parameters:
        - in: path
          name: id
          description: Transaction id
          required: true
          type: integer
        - in: body
          name: body
          description: Update transaction attributes
          required: true
          schema:
            $ref: '#/definitions/UpdateSpecificTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successully
          schema:
            $ref: '#/definitions/SpecificTransaction'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Create transaction
      description: Create a new transaction
      parameters:
      - in: path
        name: id
        description: Transaction id
        required: true
        type: integer
      - in: body
        name: body
        description: New transaction attributes
        required: true
        schema:
          $ref: '#/definitions/UpdateSpecificTransaction'
      produces:
          - application/json
      responses:
        '201':
          description: New transaction attributes created successfully
          schema:
            $ref: '#/definitions/SpecificTransaction'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error 
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete attributes
      description: Delete attributes transaction by id
      parameters:
      - in: path
        name: id
        description: Transaction attribute
        required: true
        type: integer
      produces:
        - application/json
      responses:
        '204':
          description: Transaction attributes deleted successfully
          schema:
            $ref: '#/definitions/BasicRes'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Account:
    type: object
    properties:
      date:
        type: string
      id:
        type: string
      name:
        type: string
      balance:
        type: number
      transaction:  
        type: array
        items:
          $ref: '#/definitions/Transaction'
  Transaction:
    type: object
    properties:
      fromAccountId:
        type: string
      toAccountId:
        type: string
      amount:
        type: number
      description:
        type: string
  SpecificTransaction:
    type: object
    properties:
      id:
        type: integer
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: string
      balance:
        type: number
      type:
        type: string
      category:
        type: string
      note:
        type: string
  UpdateSpecificTransaction:
    type: object
    properties:
      category:
        type: string
      note:
        type: string
  BasicRes:
    properties:
      status:
        type: integer
        description: status code
      message:
        type: string
        description: confirm message
  
